name: Golden Image Build and Test

on:
  workflow_dispatch:

env:
  GHCR_REGISTRY: ghcr.io
  GHCR_NAMESPACE: ${{ github.actor }}
  REGISTRY: ghcr.io/${{ github.actor }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  # Generate matrix dynamically
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate matrix
        id: set-matrix
        run: |
          chmod +x scripts/generate-github-matrix.sh
          {
            echo "matrix<<EOF"
            ./scripts/generate-github-matrix.sh json
            echo "EOF"
          } >> $GITHUB_OUTPUT

  # Build and test base images
  build-base-images:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
      # Only build for alpine and debian
      # RedHat removed
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build base image for LTS version
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./base-images/${{ matrix.os }}/Dockerfile.${{ matrix.version }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ matrix.os }}-base:${{ matrix.version }}
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VCS_REF=${{ github.sha }}
            VERSION=1.0.0
      - name: Test base image
        run: |
          docker run --rm ${{ env.REGISTRY }}/${{ matrix.os }}-base:${{ matrix.version }} echo "Base image test successful"

  # Generate platform matrix dynamically
  generate-platform-matrix:
    runs-on: ubuntu-latest
    needs: generate-matrix
    outputs:
      platform-matrix: ${{ steps.set-platform-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate platform matrix
        id: set-platform-matrix
        run: |
          chmod +x scripts/generate-platform-targets.sh
          {
            echo "matrix<<EOF"
            ./scripts/generate-platform-targets.sh json
            echo "EOF"
          } >> $GITHUB_OUTPUT

  # Build and test platform images
  build-platform-images:
    runs-on: ubuntu-latest
    needs: [build-base-images, generate-platform-matrix]
    strategy:
      matrix: ${{ fromJson(needs.generate-platform-matrix.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build platform image
        uses: docker/build-push-action@v5
        with:
          context: ./platform-images/${{ matrix.platform }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ matrix.platform }}-${{ matrix.platform_version }}-${{ matrix.os }}-${{ matrix.os_version }}
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VCS_REF=${{ github.sha }}
            VERSION=1.0.0
            BASE_IMAGE=${{ env.REGISTRY }}/${{ matrix.os }}-base:${{ matrix.os_version }}
            ${{ matrix.platform_upper }}_VERSION=${{ matrix.platform_version }}
      - name: Test platform image
        run: |
          docker run --rm ${{ env.REGISTRY }}/${{ matrix.platform }}-${{ matrix.platform_version }}-${{ matrix.os }}-${{ matrix.os_version }} echo "Platform image test successful"

  # Security scanning
  security-scan:
    runs-on: ubuntu-latest
    needs: [build-base-images, build-platform-images]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
      - name: Generate scan list
        id: scanlist
        run: |
          chmod +x scripts/generate-github-matrix.sh
          ./scripts/generate-github-matrix.sh scanning > scanlist.txt
          cat scanlist.txt
      - name: Scan all LTS base images
        run: |
          while read -r line; do
            if [[ $line == -* ]]; then
              image=$(echo $line | cut -d' ' -f2)
              echo "Scanning $image..."
              trivy image --severity HIGH,CRITICAL --format sarif --output trivy-$(basename $image | tr ':' '-').sarif $image
            fi
          done < <(grep '-' scanlist.txt)
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-*.sarif'

  # Integration testing
  integration-test:
    runs-on: ubuntu-latest
    needs: [build-base-images, build-platform-images]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run integration tests
        run: |
          # Test nginx platform
          docker run -d --name nginx-test -p 8080:80 ${{ env.REGISTRY }}/nginx-platform:${{ env.IMAGE_TAG }}
          sleep 10
          curl -f http://localhost:8080/health || exit 1
          docker stop nginx-test && docker rm nginx-test

          # Test python platform
          docker run --rm ${{ env.REGISTRY }}/python-platform:${{ env.IMAGE_TAG }} python3 --version

          # Test dotnet platform
          docker run --rm ${{ env.REGISTRY }}/dotnet-platform:${{ env.IMAGE_TAG }} dotnet --version
