name: Golden Image Build and Test

on:
  workflow_dispatch:

env:
  GHCR_REGISTRY: ghcr.io
  GHCR_NAMESPACE: ${{ github.repository_owner }}
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  # Generate matrix dynamically
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate matrix
        id: set-matrix
        run: |
          chmod +x scripts/generate-github-matrix.sh
          MATRIX_JSON=$(./scripts/generate-github-matrix.sh json)
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

  # Build and test base images
  build-base-images:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build base image for LTS version
        uses: docker/build-push-action@v5
        with:
          context: ./base-images/${{ matrix.os }}
          file: ./base-images/${{ matrix.os }}/Dockerfile.${{ matrix.version }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ matrix.os }}-hardened:${{ matrix.version }}
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VCS_REF=${{ github.sha }}
            VERSION=1.0.0
      - name: Test base image
        run: |
          docker run --rm ${{ env.REGISTRY }}/${{ matrix.os }}-hardened:${{ matrix.version }} echo "Base image test successful"

  # Build and test platform images
  build-platform-images:
    runs-on: ubuntu-latest
    needs: build-base-images
    strategy:
      matrix:
        platform: [nginx, openjdk, python, dotnet]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build platform image
        uses: docker/build-push-action@v5
        with:
          context: ./platform-images/${{ matrix.platform }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ matrix.platform }}-platform:${{ env.IMAGE_TAG }}
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VCS_REF=${{ github.sha }}
            VERSION=1.0.0
      - name: Test platform image
        run: |
          docker run --rm ${{ env.REGISTRY }}/${{ matrix.platform }}-platform:${{ env.IMAGE_TAG }} echo "Platform image test successful"

  # Security scanning
  security-scan:
    runs-on: ubuntu-latest
    needs: [build-base-images, build-platform-images]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
      - name: Generate scan list
        id: scanlist
        run: |
          chmod +x scripts/generate-github-matrix.sh
          ./scripts/generate-github-matrix.sh scanning > scanlist.txt
          cat scanlist.txt
      - name: Scan all LTS base images
        run: |
          while read -r line; do
            if [[ $line == -* ]]; then
              image=$(echo $line | cut -d' ' -f2)
              echo "Scanning $image..."
              trivy image --severity HIGH,CRITICAL --format sarif --output trivy-$(basename $image | tr ':' '-').sarif $image
            fi
          done < <(grep '-' scanlist.txt)
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-*.sarif'

  # Integration testing
  integration-test:
    runs-on: ubuntu-latest
    needs: [build-base-images, build-platform-images]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run integration tests
        run: |
          # Test nginx platform
          docker run -d --name nginx-test -p 8080:80 ${{ env.REGISTRY }}/nginx-platform:${{ env.IMAGE_TAG }}
          sleep 10
          curl -f http://localhost:8080/health || exit 1
          docker stop nginx-test && docker rm nginx-test

          # Test python platform
          docker run --rm ${{ env.REGISTRY }}/python-platform:${{ env.IMAGE_TAG }} python3 --version

          # Test dotnet platform
          docker run --rm ${{ env.REGISTRY }}/dotnet-platform:${{ env.IMAGE_TAG }} dotnet --version

  # Update latest tags in ACR for all LTS versions
  update-latest-tags:
    runs-on: ubuntu-latest
    needs: [build-base-images, build-platform-images, security-scan, integration-test]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Generate matrix for ACR tags
        id: acrmatrix
        run: |
          chmod +x scripts/generate-github-matrix.sh
          ./scripts/generate-github-matrix.sh scanning > scanlist.txt
          cat scanlist.txt
      - name: Update ACR tags for all LTS versions
        run: |
          while read -r line; do
            if [[ $line == -* ]]; then
              image=$(echo $line | cut -d' ' -f2)
              acr_image=${{ secrets.ACR_LOGIN_SERVER }}/$(basename $image)
              docker pull $acr_image
              docker tag $acr_image $acr_image:latest
              docker push $acr_image:latest
            fi
          done < <(grep '-' scanlist.txt) 